# Voice PDF Assistant Backend - DigitalOcean App Platform

name: voice-pdf-backend
region: nyc

services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/voice-pdf-assistant
      branch: main
      deploy_on_push: true

    source_dir: /backend

    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 8000

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: "production"
      # R2 Storage (optional - add if using Cloudflare R2)
      # - key: R2_ACCOUNT_ID
      #   value: YOUR_R2_ACCOUNT_ID
      #   type: SECRET
      # - key: R2_ACCESS_KEY_ID
      #   value: YOUR_R2_ACCESS_KEY
      #   type: SECRET
      # - key: R2_SECRET_ACCESS_KEY
      #   value: YOUR_R2_SECRET_KEY
      #   type: SECRET
      # - key: R2_BUCKET_NAME
      #   value: voice-pdf-files

    routes:
      - path: /
